### ISSUE TITLE
Total raised amounts drop trailing zeroes

### ISSUE THREAD

**Issue by mjalkio** [classy-org/classy-org-wp#19]
In @dpfavand's recent PR I noticed that trailing zeroes are dropped from total raised. For example, if someone raised $124.60, the number displayed is $124.6.

![example](https://user-images.githubusercontent.com/3981503/32473015-3e8666cc-c31a-11e7-850b-4dbc0b20471c.png)

This should be easy to resolve using the `number_format` function http://php.net/manual/en/function.number-format.php

**Comment by dpfavand** [comment]
I'm a fan of dropping cents altogether and just showing rounded numbers as it's cleaner (and matches the Classy frontend).
