### ISSUE TITLE
Campaign Overview

### ISSUE THREAD

**Issue by mattferderer** [classy-org/classy-org-wp#22]
Is "Organization overview of campaigns" still on the roadmap? We would like to add a list of campaigns for our WordPress users. If this will be a while, we can do a pull request if you like or just fork it if you don't want contributions at this time.

**Comment by mjalkio** [comment]
Hi @mattferderer, we're no longer actively developing this plugin, but we love to see pull requests from anyone using it! I've opened a PR to more accurately reflect that in the README. Do feel free to reach out if you have any questions.
