### ISSUE TITLE
Team totals may be incorrect

### ISSUE THREAD

**Issue by dpfavand** [classy-org/classy-org-wp#6]
An issue exists where team fundraising totals reported by the API may be higher than the actual team fundraising total. This appears to be caused by registration fees being credited to the team, even when the option to credit registration fees to a fundraiser's fundraising total is turned off. Not all registration fees are (incorrectly) credited towards a team and reported as total_raised by the api; it is unclear what causes this and no explanation has been provided by Classy support.

A proposed workaround is to rewrite the teams leaderboard to

1. get the top 20 teams (sort by `total_raised`)
2. for each team, get the `/overview` and grab the `donations_amount`
3. sort the 20 teams by `donations_amount`

Obviously this is not the cleanest solution:

- 1 api call is replaced by 21 calls and a sort operation
- Theoretically the team with the highest `donations_amount` may not be in the top 20 by `total_raised`

**Comment by cj-beck** [comment]
Thanks for your report.  

We have a ticket in to resolve some issues where ticket fees (aka "host fees") are being counted towards fundraising credit where they should not.  This is an issue we are intending to resolve directly in the API.  Once done, this plugin should behave appropriately without further change.

Please follow [API Release Notes](http://go.classy.org/api-updates) for release notes.

**Comment by dpfavand** [comment]
This does not appear to be an issue any longer with the new campaigns.
